# Generated by Django 4.2.20 on 2025-04-28 00:02

from django.db import migrations, models
import site_body.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_text', models.CharField(max_length=3000)),
                ('text_file', models.FileField(upload_to=site_body.models.get_file_upload_path)),
            ],
        ),
    ]
